In [1]:
import torch
import torch.nn as nn 

In [4]:
# torch.random.manual_seed(11)

linear = nn.Linear(in_features=3, out_features=2)
print(f'linear_weight: {linear.weight.data}')
print(f'linear_bias: {linear.bias.data}')

linear_weight: tensor([[ 0.0833,  0.4906, -0.2663],
        [ 0.3262, -0.2634, -0.0425]])
linear_bias: tensor([0.3085, 0.0028])


In [8]:
nn.init.zeros_(linear.weight)
nn.init.ones_(linear.weight)




/var/folders/s3/hxlfly855_9782073gc2mj2w0000gn/T/ipykernel_2097/615741997.py:3: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(linear.weight,100)
/var/folders/s3/hxlfly855_9782073gc2mj2w0000gn/T/ipykernel_2097/615741997.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  nn.init.normal(linear.weight, mean=0, std=1)


Parameter containing:
tensor([[-1.0028, -1.0008, -0.3080],
        [-0.4922,  0.8023,  0.1384]], requires_grad=True)

In [ ]:
nn.init.constant(linear.weight,100)


In [ ]:
nn.init.normal(linear.weight, mean=0, std=1)

In [7]:
nn.init.uniform(linear.weight)

/var/folders/s3/hxlfly855_9782073gc2mj2w0000gn/T/ipykernel_2097/1942631128.py:1: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(linear.weight)


Parameter containing:
tensor([[0.4578, 0.3566, 0.4831],
        [0.6752, 0.2525, 0.5272]], requires_grad=True)

In [9]:
#unchanged original tensor without _
# initial weights in such a way that variance of the activations is preserved as the data passes through the layers of the network 
# avoid both vanishing and exploding gradients 
# fan_in = forward pass
#fan_out = backward pass
#stddev = sqrt(2 / fan_in)
# best for ReLU
nn.init.kaiming_normal(linear.weight)

/var/folders/s3/hxlfly855_9782073gc2mj2w0000gn/T/ipykernel_2097/3101024978.py:1: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(linear.weight)


Parameter containing:
tensor([[ 0.0941, -1.2759, -0.3239],
        [ 0.5501,  0.6989,  0.5106]], requires_grad=True)

In [10]:
nn.init.kaiming_uniform_(linear.weight)

Parameter containing:
tensor([[-0.4480, -0.7805,  1.2044],
        [ 1.3350,  0.7301, -0.1207]], requires_grad=True)

In [11]:
#aims to set the initial weights in such a way that the variance of the activations is preserved as the data passes through the layers of the network
# stddev = sqrt(2 / (fan_in + fan_out))
# sigmoid and tanh 
nn.init.xavier_normal_(linear.weight)

Parameter containing:
tensor([[ 0.4353,  0.5509,  0.3423],
        [ 0.3515, -0.2069,  0.8365]], requires_grad=True)

In [12]:
nn.init.xavier_uniform_(linear.weight)

Parameter containing:
tensor([[ 0.4397,  1.0389,  0.0872],
        [-0.1317, -0.6195, -0.2439]], requires_grad=True)