In [12]:
import torch
import numpy as np

In [4]:
mydata1 = torch.tensor([1,2,3,4,5])
mydata1.shape

torch.Size([5])

In [6]:
mydata2 = mydata1.unsqueeze(dim=0)
print(f'在0维度上扩展维度：{mydata2,mydata2.shape}')

在0维度上扩展维度：(tensor([[1, 2, 3, 4, 5]]), torch.Size([1, 5]))


In [8]:
mydata3 = mydata1.unsqueeze(dim=1)
print(f'在1维度上扩展维度：{mydata3,mydata3.shape}')

在0维度上扩展维度：(tensor([[1],
        [2],
        [3],
        [4],
        [5]]), torch.Size([5, 1]))


In [9]:
mydata4 = mydata1.unsqueeze(dim=-1)
print(f'在-1维度上扩展维度：{mydata4,mydata4.shape}')

在-1维度上扩展维度：(tensor([[1],
        [2],
        [3],
        [4],
        [5]]), torch.Size([5, 1]))


In [11]:
mydata5 = mydata1.squeeze()
print(f'压缩维度：{mydata5,mydata5.shape}')

压缩维度：(tensor([1, 2, 3, 4, 5]), torch.Size([5]))


- tranpose and permute()

In [13]:
data = torch.tensor(np.random.randint(0,10,[3,4,5]))
print('data shape:', data.size())

data shape: torch.Size([3, 4, 5])


In [19]:
mydata2 = torch.transpose(data, 1, 2 )
print('shape:', mydata2.shape)

shape: torch.Size([3, 5, 4])


In [20]:
mydata3 = torch.transpose(data, 0,1)
mydata4 = torch.transpose(mydata3, 1,2)
print('shape:', mydata4.shape)

shape: torch.Size([4, 5, 3])


In [21]:
mydata5 = torch.permute(data, [1,2,0])
print('shape:', mydata5.shape)

shape: torch.Size([4, 5, 3])


In [23]:
mydata6 = data.permute([1,2,0])
print('shape:', mydata6.shape)

shape: torch.Size([4, 5, 3])


#### 1.3 view and contiguous()

In [24]:
torch.random.manual_seed(22)
data = torch.randint(0,10,[2,3])
print(data.shape)

torch.Size([2, 3])


In [27]:
print(data.is_contiguous())
print(data.view(-1).shape)

data1 = torch.transpose(data, 0,1)
print(data1.is_contiguous())
# view 内存一定要连续
data2 = data1.contiguous()
# data2.view(-1).shape
data2.view(3,2)

True
torch.Size([6])
False


tensor([[9, 4],
        [6, 2],
        [6, 2]])

## 拼接

In [28]:
torch.random.manual_seed(22)
data1 = torch.randint(0,10,[4,5,3])
data1

tensor([[[9, 6, 6],
         [4, 2, 2],
         [2, 1, 8],
         [0, 1, 0],
         [3, 2, 4]],

        [[4, 9, 0],
         [0, 1, 3],
         [2, 9, 7],
         [8, 4, 1],
         [7, 9, 6]],

        [[8, 1, 6],
         [1, 0, 3],
         [5, 3, 8],
         [5, 7, 7],
         [5, 1, 8]],

        [[8, 9, 5],
         [5, 2, 9],
         [0, 5, 6],
         [7, 9, 1],
         [3, 7, 5]]])

In [29]:
torch.random.manual_seed(23)
data2 = torch.randint(0,10,[4,5,3])
data2

tensor([[[1, 6, 6],
         [7, 0, 2],
         [7, 1, 4],
         [7, 5, 6],
         [3, 7, 8]],

        [[7, 5, 2],
         [9, 8, 1],
         [9, 5, 0],
         [8, 5, 6],
         [1, 1, 2]],

        [[4, 3, 3],
         [5, 1, 1],
         [9, 6, 3],
         [9, 6, 1],
         [3, 4, 1]],

        [[1, 8, 6],
         [4, 5, 2],
         [0, 6, 9],
         [3, 6, 8],
         [7, 0, 4]]])

In [30]:
print(torch.cat([data1, data2], dim=2).shape)

torch.Size([4, 5, 6])


In [31]:
print(torch.cat([data1, data2], dim=1).shape)

torch.Size([4, 10, 3])


In [32]:
print(torch.cat([data1, data2], dim=0).shape)

torch.Size([8, 5, 3])
