In [1]:
import numpy as np
import torch

In [4]:
#将数据创建为张量
print(torch.tensor(100))
print(torch.tensor([10.5, 2.3]))
print('-' *23)
data = np.random.randn(10)
print(data)
print('-' *23)
print(torch.tensor(data))
print('-' *23)
#指定形状或指定数据创建张量
print(torch.Tensor(2, 3))

tensor(100)
tensor([10.5000,  2.3000])
-----------------------
[ 0.00542678 -1.00815742 -1.57359421  2.75372367 -1.29467986  0.84396137
  1.4915734   2.47896946  0.0330479  -0.76182945]
-----------------------
tensor([ 0.0054, -1.0082, -1.5736,  2.7537, -1.2947,  0.8440,  1.4916,  2.4790,
         0.0330, -0.7618])
-----------------------
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
#指定元素类型
print(torch.IntTensor([10.5,2.3]))

tensor([10,  2], dtype=torch.int32)


/var/folders/s3/hxlfly855_9782073gc2mj2w0000gn/T/ipykernel_2291/48161279.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  print(torch.IntTensor([10.5,2.3]))


In [6]:
print(torch.FloatTensor([100]))

tensor([100.])


#### 1.2 线性张量和随机张量

In [11]:
# 在指定区间按照步长生成元素 【start, end, steps]
print(torch.arange(0,10,1)) #包左不包右

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [20]:
#在指定区间按照匀速个数生成 【start, end, steps]
print(torch.linspace(0, 10, 5))

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [13]:
#创建随机张量
print(torch.randn(2, 3))    #2行3列

tensor([[ 0.5027,  0.9655,  1.8579],
        [ 1.1472, -0.2108, -0.5966]])


In [51]:
#查看随机数种子
print(torch.random.initial_seed())
# r"""Returns the initial seed for generating random numbers as a python long

200


In [50]:
#随机树种子设置
torch.random.manual_seed(200)
#Sets the seed for generating random numbers. Returns a   `torch.Generator` object.

data = torch.randn(2,3)
print(data)
print(f'随机树种子：{torch.random.initial_seed()}')

tensor([[ 0.0144, -2.6373, -0.4331],
        [ 0.4472,  1.9159, -0.4903]])
随机树种子：200


#### 1.3 指定值张量

In [24]:
# 创建全1张量
data = torch.randn(2,3)
print(torch.ones(4, 5))
print(torch.ones_like(data))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
#创建全0张量
print(torch.zeros(3, 4))
print(torch.zeros_like(data))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
#创建全为指定值张量
torch.full([2,3], 10)

tensor([[10, 10, 10],
        [10, 10, 10]])

#### 1.4 张量的类型转换

In [32]:
#查看类型
data = torch.randn(2,3)
print(data.dtype)       #torch.float32

torch.float32


In [33]:
#将data元素类型转换为 float64 类型
print(data.type(torch.IntTensor).dtype)


torch.int32


#### 1.5 类型转换

In [3]:
torch.random.manual_seed(2)
data_tensor = torch.randint(0,10,[2,3])
print(data_tensor)
print(type(data_tensor))

tensor([[8, 7, 1],
        [4, 8, 9]])
<class 'torch.Tensor'>


In [9]:
# 使用tensor。numpy() 函数可以将张量转换为ndarray 数组， 但是共享内存
data_numpy = data_tensor.numpy().copy()
print(data_numpy)
print(type(data_numpy))

[10 15 17]
<class 'numpy.ndarray'>


#### 1.5.1 numpy to tensor 

In [8]:
# 使用from_numpy() 可以将ndarray 数组转换为Tensor， 不共享内存
data_numpy = np.array([12,15,17])
data_tensor = torch.from_numpy(data_numpy)
data_tensor[0] = 10 
print(data_numpy)
print(data_tensor)

[10 15 17]
tensor([10, 15, 17])


#### 1.7 标量

In [6]:
#对于只有一个元素的张量， 使用item（）函数将该zhi
data = torch.tensor([30,])
print(data)
print(data.item())

tensor([30])
30


#### 1.8 基本运算

In [24]:
torch.random.manual_seed(2)
ata = torch.randint(0,10,[2,3])
print(data)

tensor([[120, 150, 100],
        [110, 100, 110]])


In [26]:
print(data.add(10)) #愿数组没变
# print(data.add_(10)) #_ 愿数组变了
print(data)

tensor([[140, 170, 120],
        [130, 120, 130]])
tensor([[130, 160, 110],
        [120, 110, 120]])


In [27]:
print(data.sub(10))
# print(data.sub_(10))
print(data)

tensor([[120, 150, 100],
        [110, 100, 110]])
tensor([[130, 160, 110],
        [120, 110, 120]])


In [28]:
print(data.mul(10))
# print(data.mul_(10))
print(data)

tensor([[1300, 1600, 1100],
        [1200, 1100, 1200]])
tensor([[130, 160, 110],
        [120, 110, 120]])


In [38]:
print(data.div(10))
print(data.div_(10).long())
# print(data.div_(10))
# print(data_long)
print(data)

tensor([[13., 16., 11.],
        [12., 11., 12.]])


RuntimeError: result type Float can't be cast to the desired output type Long

In [17]:
#change to negative 
print(data.neg())

tensor([[-12, -15, -10],
        [-11, -10, -11]])


#### 1.9 点乘

In [39]:
torch.random.manual_seed(2)
data1 = torch.randint(0,10,[2,3])
print(data1)

tensor([[8, 7, 1],
        [4, 8, 9]])


In [40]:
torch.random.manual_seed(3)
data2 = torch.randint(0,10,[2,3])
print(data2)

tensor([[6, 8, 7],
        [7, 0, 0]])


In [41]:
print(torch.mul(data1, data2))

tensor([[48, 56,  7],
        [28,  0,  0]])


In [42]:
print(data1 * data2)

tensor([[48, 56,  7],
        [28,  0,  0]])


#### 1.10 矩阵乘法 点积

In [46]:
torch.random.manual_seed(22)
data1 = torch.randint(0,10,[3,4])
print(data1)

tensor([[9, 6, 6, 4],
        [2, 2, 2, 1],
        [8, 0, 1, 0]])


In [47]:
torch.random.manual_seed(23)
data2 = torch.randint(0,10,[4,5])
print(data2)

tensor([[1, 6, 6, 7, 0],
        [2, 7, 1, 4, 7],
        [5, 6, 3, 7, 8],
        [7, 5, 2, 9, 8]])


In [48]:
print(data1 @ data2)

tensor([[ 79, 152,  86, 165, 122],
        [ 23,  43,  22,  45,  38],
        [ 13,  54,  51,  63,   8]])


In [49]:
print(torch.matmul(data1,data2))

tensor([[ 79, 152,  86, 165, 122],
        [ 23,  43,  22,  45,  38],
        [ 13,  54,  51,  63,   8]])


#### 1.11 常见运算函数

In [51]:
torch.random.manual_seed(5)
#注意 tensor 必须为Float or Double 类型
data = torch.randint(0,10,[2,3],dtype=torch.float64)
print(data)

tensor([[1., 4., 7.],
        [5., 6., 0.]], dtype=torch.float64)


In [57]:
#均值
print(data.mean()) #23/6 = 3.83
print(data.mean(dim=0)) #按行 1 + 5； 4+6； 7+0
print(data.mean(dim=1)) #按列 1+4+7； 
print(data.mean(dim=-1)) #按列 1+4+7； 

tensor(3.8333, dtype=torch.float64)
tensor([3.0000, 5.0000, 3.5000], dtype=torch.float64)
tensor([4.0000, 3.6667], dtype=torch.float64)
tensor([4.0000, 3.6667], dtype=torch.float64)


In [58]:
#计算总和
print(data.sum()) #23/6 = 3.83
print(data.sum(dim=0)) #按行 1 + 5； 4+6； 7+0
print(data.sum(dim=1)) #按列 1+4+7； 

tensor(23., dtype=torch.float64)
tensor([ 6., 10.,  7.], dtype=torch.float64)
tensor([12., 11.], dtype=torch.float64)


In [59]:
#计算平方
print(torch.pow(data, 2))

tensor([[ 1., 16., 49.],
        [25., 36.,  0.]], dtype=torch.float64)


In [60]:
#计算平方根
print(data.sqrt())

tensor([[1.0000, 2.0000, 2.6458],
        [2.2361, 2.4495, 0.0000]], dtype=torch.float64)


In [61]:
# 指数计算 
print(data.exp())


tensor([[2.7183e+00, 5.4598e+01, 1.0966e+03],
        [1.4841e+02, 4.0343e+02, 1.0000e+00]], dtype=torch.float64)


In [62]:
#对数计算
print(data.log())

tensor([[0.0000, 1.3863, 1.9459],
        [1.6094, 1.7918,   -inf]], dtype=torch.float64)


#### 1.12 索引操作

In [63]:
torch.random.manual_seed(22)
data = torch.randint(0,10,[4,5])
print(data)

tensor([[9, 6, 6, 4, 2],
        [2, 2, 1, 8, 0],
        [1, 0, 3, 2, 4],
        [4, 9, 0, 0, 1]])


In [64]:
print(data[1])  #tensor([2, 2, 1, 8, 0])

tensor([2, 2, 1, 8, 0])


In [65]:
print(data[:,2])    #tensor([6, 1, 3, 0])

tensor([6, 1, 3, 0])


In [66]:
print(data[2,3])

tensor(2)


In [70]:
print(data[[1,2], [2,2]])   #tensor([1, 3])

tensor([1, 3])


In [71]:
print(data[[[1],[2]],[2,3]]) #

tensor([[1, 8],
        [3, 2]])


- 1.12.2 范围索引

In [74]:
print(data[:4, :2])

tensor([[9, 6],
        [2, 2],
        [1, 0],
        [4, 9]])


In [77]:
print(data[1:, 3:])

tensor([[8, 0],
        [2, 4],
        [0, 1]])


- 1.12.3 布尔索引

In [79]:
#第三列大于5的数据
print(data[data[:, 3] > 5])     #8 > 5

tensor([[2, 2, 1, 8, 0]])


In [87]:
#第二行大于5的数据
print(data)
print(data[:, data[1] > 5])

tensor([[9, 6, 6, 4, 2],
        [2, 2, 1, 8, 0],
        [1, 0, 3, 2, 4],
        [4, 9, 0, 0, 1]])
tensor([[4],
        [8],
        [2],
        [0]])


- 1.12.3 多维索引

In [89]:
torch.random.manual_seed(23)
data = torch.randint(0,10,[3,4,5])
print(data)

tensor([[[1, 6, 6, 7, 0],
         [2, 7, 1, 4, 7],
         [5, 6, 3, 7, 8],
         [7, 5, 2, 9, 8]],

        [[1, 9, 5, 0, 8],
         [5, 6, 1, 1, 2],
         [4, 3, 3, 5, 1],
         [1, 9, 6, 3, 9]],

        [[6, 1, 3, 4, 1],
         [1, 8, 6, 4, 5],
         [2, 0, 6, 9, 3],
         [6, 8, 7, 0, 4]]])


In [92]:
#获取0轴上的第一数据
data[0,:,:]

tensor([[1, 6, 6, 7, 0],
        [2, 7, 1, 4, 7],
        [5, 6, 3, 7, 8],
        [7, 5, 2, 9, 8]])

In [93]:
#获取1轴的第一个数据
data[:,0,:]

tensor([[1, 6, 6, 7, 0],
        [1, 9, 5, 0, 8],
        [6, 1, 3, 4, 1]])

In [94]:
#获取2轴上的第一个数据
data[:,:,0]

tensor([[1, 2, 5, 7],
        [1, 5, 4, 1],
        [6, 1, 2, 6]])

#### 1.13 形状操作

- 13.1 reshape - 

In [100]:
torch.random.manual_seed(22)
data = torch.randint(0,10,[3,4,5])
print(data.shape)
print(data.size)
# total number of elements 
data.reshape(4,5,3)
#The middle dimension is set to -1, which means it will be automatically calculated.
# The product of the dimensions must equal the total number of elements: 
# 2×middle dimension×3=60
data.reshape(2,-1,3)    

data.reshape(-1)  #整数组

torch.Size([3, 4, 5])
<built-in method size of Tensor object at 0x7fecd8a629f0>


tensor([9, 6, 6, 4, 2, 2, 2, 1, 8, 0, 1, 0, 3, 2, 4, 4, 9, 0, 0, 1, 3, 2, 9, 7,
        8, 4, 1, 7, 9, 6, 8, 1, 6, 1, 0, 3, 5, 3, 8, 5, 7, 7, 5, 1, 8, 8, 9, 5,
        5, 2, 9, 0, 5, 6, 7, 9, 1, 3, 7, 5])